services:
  db_test:
    image: postgres:16
    container_name: stylenya_db_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stylenya_test
    ports:
      - "5434:5432"
    volumes:
      - stylenya_db_test_data:/var/lib/postgresql/data

volumes:
  stylenya_db_test_data:
